In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot
from tensorflow.keras import Model
from tensorflow.keras import Sequential
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Conv2D, Input, Dropout, Activation, Dense, MaxPooling2D, Flatten, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adadelta
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
import sklearn
from sklearn.preprocessing import MinMaxScaler

In [2]:
filepath = "iot23_combined.csv"
df = pd.read_csv(filepath)

In [3]:
df

Unnamed: 0  duration  orig_bytes  resp_bytes  missed_bytes  \
0                 0  2.998796           0           0           0.0   
1                 1  0.000000           0           0           0.0   
2                 2  0.000000           0           0           0.0   
3                 3  2.998804           0           0           0.0   
4                 4  0.000000           0           0           0.0   
...             ...       ...         ...         ...           ...   
1444669       99994  0.000000           0           0           0.0   
1444670       99995  0.000000           0           0           0.0   
1444671       99996  0.000000           0           0           0.0   
1444672       99997  0.000000           0           0           0.0   
1444673       99998  0.000000           0           0           0.0   

         orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes  \
0              3.0          180.0        0.0            0.0   
1              1.0           60.0        0.0            0.0   
2              1.0           60.0        0.0            0.0   
3              3.0          180.0        0.0            0.0   
4              1.0           60.0        0.0            0.0   
...            ...            ...        ...            ...   
1444669        1.0           40.0        0.0            0.0   
1444670        1.0           40.0        0.0            0.0   
1444671        1.0           40.0        0.0            0.0   
1444672        1.0           40.0        0.0            0.0   
1444673        1.0           40.0        0.0            0.0   

                             label  ...  conn_state_RSTOS0  conn_state_RSTR  \
0        PartOfAHorizontalPortScan  ...                  0                0   
1        PartOfAHorizontalPortScan  ...                  0                0   
2        PartOfAHorizontalPortScan  ...                  0                0   
3                           Benign  ...                  0                0   
4                           Benign  ...                  0                0   
...                            ...  ...                ...              ...   
1444669  PartOfAHorizontalPortScan  ...                  0                0   
1444670  PartOfAHorizontalPortScan  ...                  0                0   
1444671  PartOfAHorizontalPortScan  ...                  0                0   
1444672  PartOfAHorizontalPortScan  ...                  0                0   
1444673  PartOfAHorizontalPortScan  ...                  0                0   

         conn_state_RSTRH  conn_state_S0  conn_state_S1  conn_state_S2  \
0                       0              1              0              0   
1                       0              1              0              0   
2                       0              1              0              0   
3                       0              1              0              0   
4                       0              1              0              0   
...                   ...            ...            ...            ...   
1444669                 0              1              0              0   
1444670                 0              1              0              0   
1444671                 0              1              0              0   
1444672                 0              1              0              0   
1444673                 0              1              0              0   

         conn_state_S3  conn_state_SF  conn_state_SH  conn_state_SHR  
0                    0              0              0               0  
1                    0              0              0               0  
2                    0              0              0               0  
3                    0              0              0               0  
4                    0              0              0               0  
...                ...            ...            ...             ...  
1444669              0              0              0            

In [4]:
del df['Unnamed: 0']

In [5]:
df['label'].value_counts()

PartOfAHorizontalPortScan     825939
Okiru                         262690
Benign                        197809
DDoS                          138777
C&C                            15100
Attack                          3915
C&C-HeartBeat                    349
C&C-FileDownload                  43
C&C-Torii                         30
FileDownload                      13
C&C-HeartBeat-FileDownload         8
C&C-Mirai                          1
Name: label, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df[['duration', 'orig_bytes', 'resp_bytes', 'missed_bytes', 'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'proto_icmp', 'proto_tcp', 'proto_udp', 'conn_state_OTH', 'conn_state_REJ', 'conn_state_RSTO', 'conn_state_RSTOS0', 'conn_state_RSTR', 'conn_state_RSTRH', 'conn_state_S0', 'conn_state_S1', 'conn_state_S2', 'conn_state_S3', 'conn_state_SF', 'conn_state_SH', 'conn_state_SHR']].values

In [8]:
X.shape

(1444674, 24)

In [9]:
Y = pd.get_dummies(df['label']).values

In [10]:
Y.shape

(1444674, 12)

In [11]:
#X = df[['duration', 'orig_bytes', 'resp_bytes', 'missed_bytes', 'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'proto_icmp', 'proto_tcp', 'proto_udp', 'conn_state_OTH', 'conn_state_REJ', 'conn_state_RSTO', 'conn_state_RSTOS0', 'conn_state_RSTR', 'conn_state_RSTRH', 'conn_state_S0', 'conn_state_S1', 'conn_state_S2', 'conn_state_S3', 'conn_state_SF', 'conn_state_SH', 'conn_state_SHR']]
#Y = df[['label']]

In [12]:
X

array([[2.998796, 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ]])

In [13]:
df

duration  orig_bytes  resp_bytes  missed_bytes  orig_pkts  \
0        2.998796           0           0           0.0        3.0   
1        0.000000           0           0           0.0        1.0   
2        0.000000           0           0           0.0        1.0   
3        2.998804           0           0           0.0        3.0   
4        0.000000           0           0           0.0        1.0   
...           ...         ...         ...           ...        ...   
1444669  0.000000           0           0           0.0        1.0   
1444670  0.000000           0           0           0.0        1.0   
1444671  0.000000           0           0           0.0        1.0   
1444672  0.000000           0           0           0.0        1.0   
1444673  0.000000           0           0           0.0        1.0   

         orig_ip_bytes  resp_pkts  resp_ip_bytes                      label  \
0                180.0        0.0            0.0  PartOfAHorizontalPortScan   
1                 60.0        0.0            0.0  PartOfAHorizontalPortScan   
2                 60.0        0.0            0.0  PartOfAHorizontalPortScan   
3                180.0        0.0            0.0                     Benign   
4                 60.0        0.0            0.0                     Benign   
...                ...        ...            ...                        ...   
1444669           40.0        0.0            0.0  PartOfAHorizontalPortScan   
1444670           40.0        0.0            0.0  PartOfAHorizontalPortScan   
1444671           40.0        0.0            0.0  PartOfAHorizontalPortScan   
1444672           40.0        0.0            0.0  PartOfAHorizontalPortScan   
1444673           40.0        0.0            0.0  PartOfAHorizontalPortScan   

         proto_icmp  ...  conn_state_RSTOS0  conn_state_RSTR  \
0                 0  ...                  0                0   
1                 0  ...                  0                0   
2                 0  ...                  0                0   
3                 0  ...                  0                0   
4                 0  ...                  0                0   
...             ...  ...                ...              ...   
1444669           0  ...                  0                0   
1444670           0  ...                  0                0   
1444671           0  ...                  0                0   
1444672           0  ...                  0                0   
1444673           0  ...                  0                0   

         conn_state_RSTRH  conn_state_S0  conn_state_S1  conn_state_S2  \
0                       0              1              0              0   
1                       0              1              0              0   
2                       0              1              0              0   
3                       0              1              0              0   
4                       0              1              0              0   
...                   ...            ...            ...            ...   
1444669                 0              1              0              0   
1444670                 0              1              0              0   
1444671                 0              1              0              0   
1444672                 0              1              0              0   
1444673                 0              1              0              0   

         conn_state_S3  conn_state_SF  conn_state_SH  conn_state_SHR  
0                    0              0              0               0  
1                    0              0              0               0  
2                    0              0              0               0  
3                    0              0              0               0  
4                    0              0              0               0  
...                ...            ...            ...             ...  
1444669              0              0              0            

In [14]:
scaler = MinMaxScaler()

In [15]:
scaler.fit(X)

MinMaxScaler()

In [16]:
normalized_x = scaler.transform(X)

In [17]:
normalized_x

array([[8.16450401e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.04174057e-05, 5.73121586e-10, 8.57558209e-08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [18]:
normalized_x.shape

(1444674, 24)

In [19]:
scaler.fit(Y)

MinMaxScaler()

In [20]:
normalized_y = scaler.transform(Y)

In [21]:
normalized_y

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(normalized_x, normalized_y, random_state=10, test_size=0.2)

In [23]:
X_train.shape

(1155739, 24)

In [24]:
model = Sequential()

In [25]:
model.add(Dense(2000, activation='relu',input_dim=24))
model.add(Dense(1500, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(800,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(400,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(150,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(12, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2000)              50000     
_________________________________________________________________
dense_1 (Dense)              (None, 1500)              3001500   
_________________________________________________________________
dropout (Dropout)            (None, 1500)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 800)               1200800   
_________________________________________________________________
dropout_1 (Dropout)          (None, 800)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 400)               320400    
_________________________________________________________________
dropout_2 (Dropout)          (None, 400)               0

In [27]:
import time

In [28]:
start = time.time()
print('program start...')
print()

history = model.fit(X_train, Y_train, epochs = 10, batch_size=256, validation_data=(X_test,Y_test),verbose=1)

print()
end = time.time()
print('program end...')
print()
print('time cost: ')
print(end - start, 'seconds')

program start...

Epoch 1/10
4515/4515 [==============================] - 26s 6ms/step - loss: 0.8835 - accuracy: 0.6902 - val_loss: 0.8618 - val_accuracy: 0.6929
Epoch 2/10
4515/4515 [==============================] - 24s 5ms/step - loss: 0.8592 - accuracy: 0.6936 - val_loss: 0.8614 - val_accuracy: 0.6934
Epoch 3/10
4515/4515 [==============================] - 24s 5ms/step - loss: 0.8590 - accuracy: 0.6942 - val_loss: 0.8605 - val_accuracy: 0.6934
Epoch 4/10
4515/4515 [==============================] - 24s 5ms/step - loss: 0.8597 - accuracy: 0.6936 - val_loss: 0.8606 - val_accuracy: 0.6934
Epoch 5/10
4515/4515 [==============================] - 24s 5ms/step - loss: 0.8576 - accuracy: 0.6944 - val_loss: 0.8611 - val_accuracy: 0.6934
Epoch 6/10
4515/4515 [==============================] - 24s 5ms/step - loss: 0.8586 - accuracy: 0.6937 - val_loss: 0.8600 - val_accuracy: 0.6934
Epoch 7/10
4515/4515 [==============================] - 24s 5ms/step - loss: 0.8577 - accuracy: 0.6943 - val_los